apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
    jenkins/jenkins-jenkins-agent: true
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: pks-cicd
    - name: preload-config-volume
      emptyDir: {}
  initContainers:
  - name: copy-ro-scripts
    image: busybox
    command: [ 'sh', '-c' ]
    args: ['mkdir -p /tmp/data; mkdir -p /tmp/config; cp /tmp/data/* /tmp/config']
    volumeMounts:
    - name: secret-volume
      mountPath: /tmp/data
    - name: preload-config-volume
      mountPath: /tmp/config
  containers:
    - name: k8s
      image: ppringle/docker-build
      command:
        - sleep
      env:
        - name: KUBECONFIG
          value: "/tmp/config/jenkins-tbs-sa"
      volumeMounts:
      - name: preload-config-volume
        mountPath: /tmp/config
      args:
        - infinity
