apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
    jenkins/jenkins-jenkins-agent: true
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: pks-cicd
    - name: preload-config-volume
      emptyDir: {}
  initContainers:
  - name: copy-ro-scripts
    image: busybox
    command: [ 'sh', '-c', 'cp /tmp/data/* /tmp/config/*' ]
    volumeMounts:
    - name: secret-volume
      mountPath: /tmp/data
    - name: preload-config-volume
      mountPath: /tmp/config
  containers:
    - name: k8s
      image: kpack/kp
      command:
        - sleep
      env:
        - name: KUBECONFIG
          value: "/tmp/config/kubeconfig-sa"
      args:
        - infinity
