apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-deploy-sa
  namespace: jenkins
secrets:
  - name: ppringle-dockerhub-creds
  - name: ppringle-github-creds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-deploy-role
rules:
  - apiGroups: [ '*' ]
    resources: [ '*' ]
    verbs: [ '*' ]
  - nonResourceURLs: [ '*' ]
    verbs: [ '*' ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-deploy-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kpack-deploy-role
subjects:
  - kind: ServiceAccount
    name: kpack-deploy-sa
    namespace: jenkins
